micronaut:
  server:
    port: 8082
  application:
    name: store
datasources:
  default:
    driverClassName: com.mysql.cj.jdbc.Driver
    db-type: mysql
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        connection:
          url: jdbc:mysql://localhost:3306/tesco
          username: root
          password: 'tesco-rules'
    reactive: true
netty:
  default:
    allocator:
      max-order: 3
